apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - dhcpd-serviceaccount.yml
  - dhcpd-role.yml
  - dhcpd-rolebinding.yml
  - dhcpd-deploy.yml

# --- ConfigMap generation for dhcpd.conf ---
configMapGenerator:
  - name: dhcpd-config
    files:
      - dhcpd.conf=config/dhcpd.conf

generatorOptions:
  disableNameSuffixHash: true
